using System;
using System.IO;
using System.Text;
using Avalonia;

namespace MeetingScribe.App;

/// <summary>
/// Process entry point. Installs process-wide unhandled-exception logging before
/// building the Avalonia app - a desktop app with no console has nowhere else for an
/// unobserved crash to go. <see cref="Avalonia.Threading.Dispatcher"/>-thread exceptions
/// (e.g. an unhandled throw inside a command handler) are additionally caught in
/// <c>App.axaml.cs</c> via <c>Dispatcher.UIThread.UnhandledException</c>; this class
/// covers everything that happens before/around/outside that - startup failures,
/// background-thread crashes, and unobserved task exceptions.
/// </summary>
internal static class Program
{
    public static string LogDirectory { get; } = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        "MeetingScribeCS",
        "logs");

    private static readonly string CrashLogPath = Path.Combine(LogDirectory, "crash.log");

    // Avalonia's designer/previewer reflects over this method by convention - keep the
    // signature and name exactly as generated by the Avalonia project templates.
    [STAThread]
    public static void Main(string[] args)
    {
        Directory.CreateDirectory(LogDirectory);

        AppDomain.CurrentDomain.UnhandledException += OnDomainUnhandledException;
        TaskScheduler.UnobservedTaskException += OnUnobservedTaskException;

        try
        {
            BuildAvaloniaApp().StartWithClassicDesktopLifetime(args);
        }
        catch (Exception ex)
        {
            LogCrash("startup", ex);
            throw;
        }
    }

    public static AppBuilder BuildAvaloniaApp() =>
        AppBuilder.Configure<App>()
            .UsePlatformDetect()
            .WithInterFont()
            .LogToTrace();

    private static void OnDomainUnhandledException(object sender, UnhandledExceptionEventArgs e)
    {
        if (e.ExceptionObject is Exception ex)
        {
            LogCrash("background thread (fatal)", ex);
        }
    }

    private static void OnUnobservedTaskException(object? sender, UnobservedTaskExceptionEventArgs e)
    {
        LogCrash("unobserved task", e.Exception);
        e.SetObserved();
    }

    internal static void LogCrash(string origin, Exception ex)
    {
        try
        {
            var text = $"[{DateTime.UtcNow:O}] ({origin}) {ex}\n\n";
            File.AppendAllText(CrashLogPath, text, Encoding.UTF8);
        }
        catch (IOException)
        {
            // Best-effort logging; a failure to write the crash log must never mask the
            // original crash or throw a second exception out of a handler.
        }
        catch (UnauthorizedAccessException)
        {
            // Same rationale as above.
        }
    }
}
